# https://qiita.com/yukin01/items/dd1cfc07abefd6a13aa5

- name: make directory
  hosts: docker_host
  tasks:
  - name: make directory
    file:
      path=/dockerroot
      state=directory
      group=root mode=0755








