# https://qiita.com/yukin01/items/dd1cfc07abefd6a13aa5

- name: docker re build
  hosts: docker_host
  tasks:
  - name: remove image flask
    docker_image:
      name: flask:rps
      state: absent
    async: 1000
    poll: 1

  - name: re build image flask
    docker_image:
      name: flask:rps
      build:
        path: /dockerroot/setup
        dockerfile: dockerfile_flask.df
      source: build
    async: 1000
    poll: 1