FROM centos:7

RUN yum install python3 -y

RUN pip3 install --upgrade pip
RUN pip3 install flask
RUN pip3 install datetime
RUN pip3 install sqlalchemy
RUN pip3 install pytest

RUN yum install unzip -y
RUN yum install iproute -y

RUN yum install python-devel mysql-devel -y
RUN yum install python3-devel -y
RUN yum install gcc -y
RUN pip3 install mysqlclient


ENV LC_ALL en_US.UTF-8

CMD source /root/setup/setup_rps_test_flask.sh






