# https://qiita.com/yukin01/items/dd1cfc07abefd6a13aa5

- name: apt update
  hosts: vert
  tasks:
  - name: apt update
    apt:
      update_cache: yes
    async: 1000
    poll: 1

- name: install pip by apt
  hosts: vert
  tasks:
  - name: install pip
    apt:
      name: python3-pip
      state: present
    become: yes
      
- name: install pkg by pip
  hosts: vert
  tasks:
  - name: install docker sdk
    pip:
      name: docker
    become: yes

  - name: Installing docker compose
    pip:
      name: docker-compose
      state: present











