FROM centos:7

RUN yum localinstall http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm -y

RUN yum install mysql-community-server -y

RUN yum install iproute -y
RUN yum install wget -y
RUN yum install openssh-clients -y

ARG ip_host=10.255.255.1
scp root@${ip_host}:/root/dockerfiles/001_python_tool/secret.txt /root/

RUN systemctl enable mysqld