version: '3'
services:
  lb:
    image: haproxy:flask
    container_name: lb
    networks:
      - backend
    ports:
      - 8080:8080
    expose:
      - '8080'
    volumes:
      - /root/dockerfiles/001_python_tool/setup:/setup:ro
    depends_on:
      - "app001"
      - "app002"
  app001:
    image: python36:flask
    container_name: flask001
    hostname: flask001
    networks:
      - backend
    volumes:
      - /root/dockerfiles/001_python_tool/setup:/setup:ro
    depends_on:
      - "mysql"
  app002:
    image: python36:flask
    container_name: flask002
    hostname: flask002
    networks:
      - backend
    volumes:
      - /root/dockerfiles/001_python_tool/setup:/setup:ro
    depends_on:
      - "mysql"
  mysql:
    image: mysql:flask 
    container_name: mysql
    networks:
      - backend
    volumes:
      - /root/dockerfiles/001_python_tool/setup/mysql_setup:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${root_pass}
    depends_on:
      - "fluentd"
  fluentd:
    image: fluentd:flask
    container_name: fluentd
    networks:
      - backend
    expose:
      # default port 5140/tcp,24224/tcp
      - '24220'
      - '24221'
      - '24280'
    volumes:
      - /root/dockerfiles/001_python_tool/setup:/setup:ro
      - /root/dockerfiles/001_python_tool/fluentd:/fluentd
networks:
    backend:

